// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: proto/bybit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bybit_GetAllAssetWithNetworks_FullMethodName = "/bybit.Bybit/GetAllAssetWithNetworks"
)

// BybitClient is the client API for Bybit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BybitClient interface {
	GetAllAssetWithNetworks(ctx context.Context, in *GetAllAssetWithNetworksRequest, opts ...grpc.CallOption) (*GetAllAssetWithNetworksRespose, error)
}

type bybitClient struct {
	cc grpc.ClientConnInterface
}

func NewBybitClient(cc grpc.ClientConnInterface) BybitClient {
	return &bybitClient{cc}
}

func (c *bybitClient) GetAllAssetWithNetworks(ctx context.Context, in *GetAllAssetWithNetworksRequest, opts ...grpc.CallOption) (*GetAllAssetWithNetworksRespose, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAssetWithNetworksRespose)
	err := c.cc.Invoke(ctx, Bybit_GetAllAssetWithNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BybitServer is the server API for Bybit service.
// All implementations must embed UnimplementedBybitServer
// for forward compatibility.
type BybitServer interface {
	GetAllAssetWithNetworks(context.Context, *GetAllAssetWithNetworksRequest) (*GetAllAssetWithNetworksRespose, error)
	mustEmbedUnimplementedBybitServer()
}

// UnimplementedBybitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBybitServer struct{}

func (UnimplementedBybitServer) GetAllAssetWithNetworks(context.Context, *GetAllAssetWithNetworksRequest) (*GetAllAssetWithNetworksRespose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAssetWithNetworks not implemented")
}
func (UnimplementedBybitServer) mustEmbedUnimplementedBybitServer() {}
func (UnimplementedBybitServer) testEmbeddedByValue()               {}

// UnsafeBybitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BybitServer will
// result in compilation errors.
type UnsafeBybitServer interface {
	mustEmbedUnimplementedBybitServer()
}

func RegisterBybitServer(s grpc.ServiceRegistrar, srv BybitServer) {
	// If the following call pancis, it indicates UnimplementedBybitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bybit_ServiceDesc, srv)
}

func _Bybit_GetAllAssetWithNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAssetWithNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BybitServer).GetAllAssetWithNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bybit_GetAllAssetWithNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BybitServer).GetAllAssetWithNetworks(ctx, req.(*GetAllAssetWithNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bybit_ServiceDesc is the grpc.ServiceDesc for Bybit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bybit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bybit.Bybit",
	HandlerType: (*BybitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllAssetWithNetworks",
			Handler:    _Bybit_GetAllAssetWithNetworks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bybit.proto",
}
